#!/bin/bash -l
set -e 

#$ -P cjdgenomics
#$ -cwd
#$ -j y
#$ -N snakemakerun      #Give job name
#$ -pe omp 8
#$ -l mem_per_core=8G
#S -l h_rt=24:00:00

module load miniconda/23.11.0
module load snakemake/8.11.3
mamba activate /share/pkg.8/snakemake/8.11.3/install/snakemake

snakemake -s workflow/Snakefile --unlock --directory "/restricted/projectnb/cjdgenomics/CJD_GenomicsVariantCalling_20240430/"

# snakemake -s workflow/Snakefile --sdm conda --cores 8 --jobs 22 --latency-wait 100 \
#  --executor cluster-generic --cluster-generic-submit-cmd "qsub -P cjdgenomics -pe omp {threads} -l mem_per_core=8G -cwd -j y -N varcallpipeline" \
#  --directory "/restricted/projectnb/cjdgenomics/CJD_GenomicsVariantCalling_20240430/" 

# The following code will run all the other files even if the script is updated
snakemake -s workflow/Snakefile --sdm conda --cores 8 --jobs 22 --latency-wait 100 --rerun-triggers mtime\
--executor cluster-generic --cluster-generic-submit-cmd "qsub -P cjdgenomics -pe omp {threads} -l mem_per_core=8G -cwd -j y -N varcallpipeline" \
--directory "/restricted/projectnb/cjdgenomics/CJD_GenomicsVariantCalling_20240430/" --latency-wait 100 --rerun-triggers mtime

# This it to check the dry run of the pipeline
# snakemake -s workflow/Snakefile -np -d "/restricted/projectnb/cjdgenomics/CJD_GenomicsVariantCalling_20240430/"
